location / {
        root /home/mirror/downloads;
        index index.html;
        autoindex on;
        autoindex_format xml;
        autoindex_localtime on;
        xslt_stylesheet /home/mirror/downloads/.autoindex.xslt;
        xslt_string_param path $uri;

        location ~ ^/\.(style\.css|logo\.svg|autoindex\.xslt|search\.js)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
        }

        location ~ ^/(.*/(config\.seed|sha256sums|sha256sums\.gpg|sha256sums\.asc|sha256sums\.sig|Packages|Packages\.gpg|Packages\.manifest|Packages\.sig|.+\.buildinfo))$ {
                default_type text/plain;
        }
}
